#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPS24_BattlePassTileEmpty

#include "Basic.hpp"

#include "BattlePassBase_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPS24_BattlePassTileEmpty.BPS24_BattlePassTileEmpty_C
// 0x0000 (0x1540 - 0x1540)
class UBPS24_BattlePassTileEmpty_C final : public UFortBattlePassTileBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPS24_BattlePassTileEmpty_C">();
	}
	static class UBPS24_BattlePassTileEmpty_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPS24_BattlePassTileEmpty_C>();
	}
};

}

