#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HmxAudio

#include "Basic.hpp"

#include "HmxCore_structs.hpp"


namespace SDK
{

// Enum HmxAudio.EHarmonixHandleValidity
// NumValues: 0x0003
enum class EHarmonixHandleValidity : uint8
{
	Invalid                                  = 0,
	Valid                                    = 1,
	EHarmonixHandleValidity_MAX              = 2,
};

// Enum HmxAudio.EOldMusicClockState
// NumValues: 0x0004
enum class EOldMusicClockState : uint8
{
	kStopped                                 = 0,
	kPaused                                  = 1,
	kRunning                                 = 2,
	EOldMusicClockState_MAX                  = 3,
};

// Enum HmxAudio.EOffsetType
// NumValues: 0x0006
enum class EOffsetType : uint8
{
	kMs                                      = 0,
	kTicks                                   = 1,
	kBeats                                   = 2,
	kMeasures                                = 3,
	kPulses                                  = 4,
	EOffsetType_MAX                          = 5,
};

// Enum HmxAudio.ELengthType
// NumValues: 0x0005
enum class ELengthType : uint8
{
	kTicks                                   = 0,
	kBeats                                   = 1,
	kMeasures                                = 2,
	kPulse                                   = 3,
	ELengthType_MAX                          = 4,
};

// Enum HmxAudio.EOldScheduleResult
// NumValues: 0x0003
enum class EOldScheduleResult : uint8
{
	Success                                  = 0,
	Failed                                   = 1,
	EOldScheduleResult_MAX                   = 2,
};

// Enum HmxAudio.ECrushedBitDepth
// NumValues: 0x0011
enum class ECrushedBitDepth : uint8
{
	SixteenBit                               = 0,
	Fifteen                                  = 1,
	Fourteen                                 = 2,
	Thirteen                                 = 3,
	Twelve                                   = 4,
	Eleven                                   = 5,
	Ten                                      = 6,
	Nine                                     = 7,
	Eight                                    = 8,
	Seven                                    = 9,
	Six                                      = 10,
	Five                                     = 11,
	Four                                     = 12,
	Three                                    = 13,
	Two                                      = 14,
	One                                      = 15,
	ECrushedBitDepth_MAX                     = 16,
};

// Enum HmxAudio.EHarmonixDelayFilterType
// NumValues: 0x0004
enum class EHarmonixDelayFilterType : uint8
{
	LowPass                                  = 0,
	HighPass                                 = 1,
	BandPass                                 = 2,
	EHarmonixDelayFilterType_MAX             = 3,
};

// Enum HmxAudio.EHarmonixDelayStereoType
// NumValues: 0x0006
enum class EHarmonixDelayStereoType : uint8
{
	Default                                  = 0,
	CustomSpread                             = 1,
	PingPongForceLR                          = 2,
	PingPongSum                              = 3,
	PingPongIndividual                       = 4,
	EHarmonixDelayStereoType_MAX             = 5,
};

// Enum HmxAudio.EDistortionType
// NumValues: 0x0009
enum class EDistortionType : uint8
{
	Clean                                    = 0,
	Warm                                     = 1,
	Clip                                     = 2,
	Soft                                     = 3,
	Asymmetric                               = 4,
	Cruncher                                 = 5,
	CaptCrunch                               = 6,
	Rectifier                                = 7,
	EDistortionType_MAX                      = 8,
};

// Enum HmxAudio.EDistortionFilterType
// NumValues: 0x0007
enum class EDistortionFilterType : uint8
{
	LowPass                                  = 0,
	HighPass                                 = 1,
	BandPass                                 = 2,
	Peaking                                  = 3,
	LowShelf                                 = 4,
	HighShelf                                = 5,
	EDistortionFilterType_MAX                = 6,
};

// Enum HmxAudio.EHarmonixFlangerShapes
// NumValues: 0x0006
enum class EHarmonixFlangerShapes : uint8
{
	Sine                                     = 0,
	Square                                   = 1,
	SawUp                                    = 2,
	SawDown                                  = 3,
	Triangle                                 = 4,
	EHarmonixFlangerShapes_MAX               = 5,
};

// Enum HmxAudio.EHarmonixPhaserShapes
// NumValues: 0x0006
enum class EHarmonixPhaserShapes : uint8
{
	Sine                                     = 0,
	Square                                   = 1,
	SawUp                                    = 2,
	SawDown                                  = 3,
	Triangle                                 = 4,
	EHarmonixPhaserShapes_MAX                = 5,
};

// Enum HmxAudio.EHarmonixTapeStartStopTransportState
// NumValues: 0x0003
enum class EHarmonixTapeStartStopTransportState : uint8
{
	Playing                                  = 0,
	Stoppped                                 = 1,
	EHarmonixTapeStartStopTransportState_MAX = 2,
};

// Enum HmxAudio.ESynchronizationType
// NumValues: 0x0004
enum class ESynchronizationType : uint8
{
	kNone                                    = 0,
	kNextBeat                                = 1,
	kNextMeasure                             = 2,
	ESynchronizationType_MAX                 = 3,
};

// Enum HmxAudio.EMidiMsgType
// NumValues: 0x0004
enum class EMidiMsgType : uint8
{
	kText                                    = 0,
	kNoteOn                                  = 1,
	kNoteOff                                 = 2,
	EMidiMsgType_MAX                         = 3,
};

// Enum HmxAudio.EBTLengthType
// NumValues: 0x0003
enum class EBTLengthType : uint8
{
	kBeat                                    = 0,
	kMeasure                                 = 1,
	EBTLengthType_MAX                        = 2,
};

// Enum HmxAudio.EAudioClipStartPosition
// NumValues: 0x0009
enum class EAudioClipStartPosition : uint8
{
	kImmediate                               = 0,
	kOnNextDownbeat                          = 1,
	kOnNextBeat                              = 2,
	kOnNextEighth                            = 3,
	kOnTickInBar                             = 4,
	kOnAbsoluteTick                          = 5,
	kSubdivision                             = 6,
	kNumStartPositions                       = 7,
	EAudioClipStartPosition_MAX              = 8,
};

// Enum HmxAudio.EMusicalSubdivision
// NumValues: 0x0009
enum class EMusicalSubdivision : uint8
{
	Noop                                     = 0,
	Whole                                    = 1,
	Half                                     = 2,
	Quarter                                  = 4,
	Eighth                                   = 8,
	Sixteenth                                = 16,
	Thirtysecond                             = 32,
	Sixtyforth                               = 64,
	EMusicalSubdivision_MAX                  = 65,
};

// Enum HmxAudio.EWaitAtLeastMode
// NumValues: 0x0004
enum class EWaitAtLeastMode : uint8
{
	kNone                                    = 0,
	kSecs                                    = 1,
	kTicks                                   = 2,
	EWaitAtLeastMode_MAX                     = 3,
};

// Enum HmxAudio.EPlayEmitterFindMethod
// NumValues: 0x0008
enum class EPlayEmitterFindMethod : uint8
{
	kDefault                                 = 0,
	kSearch                                  = 1,
	kSpecificEmitter                         = 2,
	kTaggedEmitterOnThisActor                = 3,
	kTaggedEmitterOnSpecifiedActor           = 4,
	kTaggedEmitterOnAnyActor                 = 5,
	kSpecificEmitterOnTaggedActor            = 6,
	EPlayEmitterFindMethod_MAX               = 7,
};

// Enum HmxAudio.ESyncEmitterFindMethod
// NumValues: 0x0009
enum class ESyncEmitterFindMethod : uint8
{
	kDefault                                 = 0,
	kSearch                                  = 1,
	kSpecificEmitter                         = 2,
	kTaggedEmitterOnThisActor                = 3,
	kTaggedEmitterOnSpecifiedActor           = 4,
	kTaggedEmitterOnAnyActor                 = 5,
	kSpecificEmittorOnTaggedActor            = 6,
	kAsPlay                                  = 7,
	ESyncEmitterFindMethod_MAX               = 8,
};

// Enum HmxAudio.FLookAheadType
// NumValues: 0x0003
enum class EFLookAheadType : uint8
{
	kTicks                                   = 0,
	kTime                                    = 1,
	FLookAheadType_MAX                       = 2,
};

// Enum HmxAudio.FMidiSourceType
// NumValues: 0x0004
enum class EFMidiSourceType : uint8
{
	MusicEmittersTimeAuthority               = 0,
	MusicPlayersCurrentMusic                 = 1,
	SpecificMusicHandle                      = 2,
	FMidiSourceType_MAX                      = 3,
};

// Enum HmxAudio.EHoldOffUnits
// NumValues: 0x0004
enum class EHoldOffUnits : uint8
{
	kNone                                    = 0,
	kTicks                                   = 1,
	kMs                                      = 2,
	EHoldOffUnits_MAX                        = 3,
};

// Enum HmxAudio.EMusicalUnit
// NumValues: 0x0004
enum class EMusicalUnit : uint8
{
	kBeatSubdivision                         = 0,
	kBarBoundary                             = 1,
	kAbsoluteMBT                             = 2,
	EMusicalUnit_MAX                         = 3,
};

// Enum HmxAudio.EMTSResult
// NumValues: 0x0003
enum class EMTSResult : uint8
{
	Failed                                   = 0,
	Succeeded                                = 1,
	EMTSResult_MAX                           = 2,
};

// Enum HmxAudio.EMusicClipUnmutePoint
// NumValues: 0x0006
enum class EMusicClipUnmutePoint : uint8
{
	Immediate                                = 0,
	NextSixteenth                            = 1,
	NextEigth                                = 2,
	NextQuarter                              = 3,
	NextDownbeat                             = 4,
	EMusicClipUnmutePoint_MAX                = 5,
};

// Enum HmxAudio.EMusicClipSyncOptions
// NumValues: 0x0005
enum class EMusicClipSyncOptions : uint8
{
	Wild                                     = 0,
	TimeAuthority                            = 1,
	TimeFollower                             = 2,
	AssumeTimeAuthority                      = 3,
	EMusicClipSyncOptions_MAX                = 4,
};

// Enum HmxAudio.EMusicClipTimelineMapping
// NumValues: 0x0008
enum class EMusicClipTimelineMapping : uint8
{
	DO_NOT_USE                               = 0,
	FromStart                                = 1,
	FromNextDownbeat                         = 2,
	FromSectionMarkers                       = 3,
	FromNearestBeat                          = 4,
	FromSpecificTick                         = 5,
	FromNextBeat                             = 6,
	EMusicClipTimelineMapping_MAX            = 7,
};

// Enum HmxAudio.EMusicClipSpeedConfigMode
// NumValues: 0x0003
enum class EMusicClipSpeedConfigMode : uint8
{
	SpeedFactor                              = 0,
	BPM                                      = 1,
	EMusicClipSpeedConfigMode_MAX            = 2,
};

// Enum HmxAudio.EMidiChannels
// NumValues: 0x0011
enum class EMidiChannels : uint8
{
	kCh0                                     = 0,
	kCh1                                     = 1,
	kCh2                                     = 2,
	kCh3                                     = 3,
	kCh4                                     = 4,
	kCh5                                     = 5,
	kCh6                                     = 6,
	kCh7                                     = 7,
	kCh8                                     = 8,
	kCh9                                     = 9,
	kCh10                                    = 10,
	kCh11                                    = 11,
	kCh12                                    = 12,
	kCh13                                    = 13,
	kCh14                                    = 14,
	kCh15                                    = 15,
	EMidiChannels_MAX                        = 16,
};

// Enum HmxAudio.FAudioContinuationMode
// NumValues: 0x000A
enum class EFAudioContinuationMode : uint8
{
	kOneshot                                 = 0,
	kRepeatOnDownbeats                       = 1,
	kRepeatOnQuarters                        = 2,
	kRepeatOnEigths                          = 3,
	kRepeatOnEigthTriplets                   = 4,
	kRepeatOn16ths                           = 5,
	kRepeatOnSpecificTickInBar               = 6,
	kStickyOnScheduledStart                  = 7,
	kNumContinuationModes                    = 8,
	FAudioContinuationMode_MAX               = 9,
};

// Enum HmxAudio.EMidiControllerID
// NumValues: 0x002C
enum class EMidiControllerID : uint8
{
	PresetSelection                          = 0,
	PortamentoTime                           = 5,
	Volume                                   = 7,
	PanRight                                 = 10,
	Expression                               = 11,
	BitCrushWetMix                           = 14,
	BitCrushLevel                            = 15,
	BitCrushSampleHold                       = 16,
	LFO0Frequency                            = 22,
	LFO1Frequency                            = 23,
	LFO0Depth                                = 24,
	LFO1Depth                                = 25,
	DelayTime                                = 26,
	DelayDryGain                             = 27,
	DelayWetGain                             = 28,
	DelayFeedback                            = 29,
	CoarsePitchBend                          = 30,
	SampleStartTime                          = 31,
	SubStreamVol1                            = 52,
	SubStreamVol2                            = 53,
	SubStreamVol3                            = 54,
	SubStreamVol4                            = 55,
	SubStreamVol5                            = 56,
	SubStreamVol6                            = 57,
	SubStreamVol7                            = 58,
	SubStreamVol8                            = 59,
	DelayEQEnabled                           = 60,
	DelayEQType                              = 61,
	DelayEQFreq                              = 62,
	DelayEQQ                                 = 63,
	PortamentoSwitch                         = 65,
	FilterQ                                  = 71,
	Release                                  = 72,
	Attack                                   = 73,
	FilterFrequency                          = 74,
	ElastiqueEnvelopeOrder                   = 79,
	DelayLFOBeatSync                         = 80,
	DelayLFOEnabled                          = 81,
	DelayLFORate                             = 82,
	DelayLFODepth                            = 83,
	DelayStereoType                          = 84,
	DelayPanLeft                             = 85,
	DelayPanRight                            = 86,
	EMidiControllerID_MAX                    = 87,
};

// Enum HmxAudio.EVorbisMemoryScheme
// NumValues: 0x0005
enum class EVorbisMemoryScheme : uint8
{
	None                                     = 0,
	Platform                                 = 1,
	PrivateAllocator                         = 2,
	PerStreamStack                           = 3,
	EVorbisMemoryScheme_MAX                  = 4,
};

// Enum HmxAudio.EAudioTransportState
// NumValues: 0x0008
enum class EAudioTransportState : uint8
{
	Invalid                                  = 0,
	PreBuffering                             = 1,
	PlayRequested                            = 2,
	Playing                                  = 3,
	Paused                                   = 4,
	Stopped                                  = 5,
	Stopping                                 = 6,
	EAudioTransportState_MAX                 = 7,
};

// Enum HmxAudio.EParamExists
// NumValues: 0x0003
enum class EParamExists : uint8
{
	DoesExist                                = 0,
	DoesNotExist                             = 1,
	EParamExists_MAX                         = 2,
};

// Enum HmxAudio.EPostFadeOption
// NumValues: 0x0003
enum class EPostFadeOption : uint8
{
	KeepPlaying                              = 0,
	Stop                                     = 1,
	EPostFadeOption_MAX                      = 2,
};

// Enum HmxAudio.EMusicFindResults
// NumValues: 0x0003
enum class EMusicFindResults : uint8
{
	NotFound                                 = 0,
	Found                                    = 1,
	EMusicFindResults_MAX                    = 2,
};

// Enum HmxAudio.FMusicUnmutePoint
// NumValues: 0x0008
enum class EFMusicUnmutePoint : uint8
{
	kUnmutePoint_Immediate                   = 0,
	kUnmutePoint_NextSixteenth               = 1,
	kUnmutePoint_NextEighth                  = 2,
	kUnmutePoint_NextQuarter                 = 3,
	kUnmutePoint_NextDownbeat                = 4,
	kUnmutePoint_SpecificLocalTick           = 5,
	kUnmutePoint_SpecificMasterTick          = 6,
	kUnmutePoint_MAX                         = 7,
};

// Enum HmxAudio.FMusicSyncOptions
// NumValues: 0x0004
enum class EFMusicSyncOptions : uint8
{
	kSync_Wild                               = 0,
	kSync_Master                             = 1,
	kSync_Slave                              = 2,
	kSync_MAX                                = 3,
};

// Enum HmxAudio.FMusicTimelineMapping
// NumValues: 0x0008
enum class EFMusicTimelineMapping : uint8
{
	kTimelineMapping_NOT_USED                = 0,
	kTimelineMapping_FromStart               = 1,
	kTimelineMapping_FromNextDownbeat        = 2,
	kTimelineMapping_FromSectionMarkers      = 3,
	kTimelineMapping_FromNearestBeat         = 4,
	kTimelineMapping_FromSpecificTick        = 5,
	kTimelineMapping_FromNextBeat            = 6,
	kTimelineMapping_MAX                     = 7,
};

// Enum HmxAudio.EPostFadeOptionEnum
// NumValues: 0x0003
enum class EPostFadeOptionEnum : uint8
{
	kPostFadeOption_None                     = 0,
	kPostFadeOption_Stop                     = 1,
	kPostFadeOption_MAX                      = 2,
};

// Enum HmxAudio.FStretcherAlgorithm
// NumValues: 0x0006
enum class EFStretcherAlgorithm : uint8
{
	kAsAuthored                              = 0,
	kDefault                                 = 1,
	kPro                                     = 2,
	kEffWithFormant                          = 3,
	kMobile                                  = 4,
	FStretcherAlgorithm_MAX                  = 5,
};

// Enum HmxAudio.FFormantHandling
// NumValues: 0x0004
enum class EFFormantHandling : uint8
{
	kAsAuthored                              = 0,
	kCorrected                               = 1,
	kUncorrected                             = 2,
	FFormantHandling_MAX                     = 3,
};

// Enum HmxAudio.FInstrumentRenderMode
// NumValues: 0x0004
enum class EFInstrumentRenderMode : uint8
{
	Parent                                   = 0,
	PreFxChild                               = 1,
	PostFxChild                              = 2,
	FInstrumentRenderMode_MAX                = 3,
};

// ScriptStruct HmxAudio.HarmonixDistortionBiquadSettings
// 0x0010 (0x0010 - 0x0000)
struct FHarmonixDistortionBiquadSettings final
{
public:
	bool                                          Enabled;                                           // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EDistortionFilterType                         Shape;                                             // 0x0001(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2[0x2];                                        // 0x0002(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Frequency;                                         // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Q;                                                 // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         GainDb;                                            // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.HarmonixDistortionFilterSettings
// 0x0018 (0x0018 - 0x0000)
struct FHarmonixDistortionFilterSettings final
{
public:
	struct FHarmonixDistortionBiquadSettings      biquad;                                            // 0x0000(0x0010)(Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	bool                                          PreClip;                                           // 0x0010(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Passes;                                            // 0x0014(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.MusicalTimeSpan
// 0x0010 (0x0010 - 0x0000)
struct FMusicalTimeSpan final
{
public:
	ELengthType                                   lengthType;                                        // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Length;                                            // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EOffsetType                                   offsetType;                                        // 0x0008(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Offset;                                            // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.HarmonixBitCrusherEffectSettings
// 0x0018 (0x0018 - 0x0000)
struct FHarmonixBitCrusherEffectSettings final
{
public:
	bool                                          Enabled;                                           // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         InputVolumeDb;                                     // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ECrushedBitDepth                              Bits;                                              // 0x0008(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         SampleAndHoldFactor;                               // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Depth;                                             // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         OutputVolumeDb;                                    // 0x0014(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.HarmonixBufferUtilEffectSettings
// 0x0001 (0x0001 - 0x0000)
struct FHarmonixBufferUtilEffectSettings final
{
public:
	bool                                          Enabled;                                           // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.HarmonixDelayEffectSettings
// 0x003C (0x003C - 0x0000)
struct FHarmonixDelayEffectSettings final
{
public:
	bool                                          Enabled;                                           // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ETempoListenerTimeSyncOption                  TimeSyncOption;                                    // 0x0001(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2[0x2];                                        // 0x0002(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         TimeSeconds;                                       // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Tempo;                                             // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DryDb;                                             // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         WetDb;                                             // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         FeedbackDb;                                        // 0x0014(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          EQEnabled;                                         // 0x0018(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EHarmonixDelayFilterType                      EQType;                                            // 0x0019(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1A[0x2];                                       // 0x001A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         EQFreq;                                            // 0x001C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         EQQ;                                               // 0x0020(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          LFOEnabled;                                        // 0x0024(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ETempoListenerTimeSyncOption                  LFOTimeSyncOption;                                 // 0x0025(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_26[0x2];                                       // 0x0026(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         LFORate;                                           // 0x0028(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         LFODepth;                                          // 0x002C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EHarmonixDelayStereoType                      StereoType;                                        // 0x0030(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_31[0x3];                                       // 0x0031(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         PanLeft;                                           // 0x0034(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         PanRight;                                          // 0x0038(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.HarmonixDistortionEffectSettings
// 0x0060 (0x0060 - 0x0000)
struct FHarmonixDistortionEffectSettings final
{
public:
	bool                                          Enabled;                                           // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         InputVolumeDb;                                     // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         OutputVolumeDb;                                    // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         WetDryMix;                                         // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DCOffset;                                          // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EDistortionType                               Algorithm;                                         // 0x0014(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Oversample;                                        // 0x0015(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_16[0x2];                                       // 0x0016(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHarmonixDistortionFilterSettings      Filter1;                                           // 0x0018(0x0018)(Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	struct FHarmonixDistortionFilterSettings      Filter2;                                           // 0x0030(0x0018)(Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	struct FHarmonixDistortionFilterSettings      Filter3;                                           // 0x0048(0x0018)(Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.HarmonixFlangerEffectSettings
// 0x0028 (0x0028 - 0x0000)
struct FHarmonixFlangerEffectSettings final
{
public:
	bool                                          Enabled;                                           // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Depth;                                             // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DelayTimeMs;                                       // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EHarmonixFlangerShapes                        Shape;                                             // 0x000C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Rate;                                              // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Feedback;                                          // 0x0014(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Invert;                                            // 0x0018(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Excursion;                                         // 0x001C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ETempoListenerTimeSyncOption                  TimeSyncOption;                                    // 0x0020(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         TempoSyncPhaseOffset;                              // 0x0024(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.HarmonixPhaserEffectSettings
// 0x0028 (0x0028 - 0x0000)
struct FHarmonixPhaserEffectSettings final
{
public:
	bool                                          Enabled;                                           // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         WetDryMix;                                         // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         OscDepth;                                          // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Feedback;                                          // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Poles;                                             // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EHarmonixPhaserShapes                         Shape;                                             // 0x0014(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Rate;                                              // 0x0018(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ETempoListenerTimeSyncOption                  TimeSyncOption;                                    // 0x001C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Color;                                             // 0x0020(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         PhaseShift;                                        // 0x0024(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.HarmonixStutterEditEffectSettings
// 0x0010 (0x0010 - 0x0000)
struct FHarmonixStutterEditEffectSettings final
{
public:
	bool                                          Enabled;                                           // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          FadeEnabled;                                       // 0x0001(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          AllowPassThrough;                                  // 0x0002(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          SilenceWhileScheduled;                             // 0x0003(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          VarispeedForTempoChanges;                          // 0x0004(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         MaxCaptureSeconds;                                 // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   InstanceName;                                      // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.HarmonixTapeStartStopEffectSettings
// 0x000C (0x000C - 0x0000)
struct FHarmonixTapeStartStopEffectSettings final
{
public:
	bool                                          Enabled;                                           // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         TransitionDurationInBeats;                         // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EHarmonixTapeStartStopTransportState          Transport;                                         // 0x0008(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct HmxAudio.HarmonixTremoloEffectSettings
// 0x0018 (0x0018 - 0x0000)
struct FHarmonixTremoloEffectSettings final
{
public:
	bool                                          Enabled;                                           // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Depth;                                             // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ETempoListenerTimeSyncOption                  TimeSyncOption;                                    // 0x0008(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         LFORate;                                           // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         LfoShape;                                          // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          InvertLfo;                                         // 0x0014(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct HmxAudio.HarmonixVibeEffectSettings
// 0x002C (0x002C - 0x0000)
struct FHarmonixVibeEffectSettings final
{
public:
	bool                                          Enabled;                                           // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         VolumeDb;                                          // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         WetDryMix;                                         // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         QuadratureFrequency1;                              // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         QuadratureFrequency2;                              // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         QuadratureFrequency3;                              // 0x0014(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         QuadratureFrequency4;                              // 0x0018(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ETempoListenerTimeSyncOption                  TimeSyncOption;                                    // 0x001C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         LFORate;                                           // 0x0020(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         LfoShape;                                          // 0x0024(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         LFODepth;                                          // 0x0028(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.HarmonixWahEffectSettings
// 0x0024 (0x0024 - 0x0000)
struct FHarmonixWahEffectSettings final
{
public:
	bool                                          Enabled;                                           // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         VolumeDb;                                          // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         OpenFrequency;                                     // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         OpenQ;                                             // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ClosedFrequency;                                   // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ClosedQ;                                           // 0x0014(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          SteepFilters;                                      // 0x0018(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Auto;                                              // 0x0019(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ETempoListenerTimeSyncOption                  TimeSyncOption;                                    // 0x001A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1B[0x1];                                       // 0x001B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         LFORate;                                           // 0x001C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         LfoShape;                                          // 0x0020(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.RemapRecord
// 0x0008 (0x0008 - 0x0000)
struct FRemapRecord final
{
public:
	class FName                                   DestTrackName;                                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         DestTrackIndex;                                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.TickSpan
// 0x0008 (0x0008 - 0x0000)
struct FTickSpan final
{
public:
	int32                                         Offset;                                            // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Length;                                            // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.MidiMusicTimeSlotArgs
// 0x0018 (0x0018 - 0x0000)
struct FMidiMusicTimeSlotArgs final
{
public:
	struct FTickSpan                              TickSpan;                                          // 0x0000(0x0008)(Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	TScriptInterface<class IMidiMusicInterface>   MusicItem;                                         // 0x0008(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.MidiNote
// 0x0001 (0x0001 - 0x0000)
struct FMidiNote final
{
public:
	uint8                                         NoteNumber;                                        // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.MusicalPlayerRuntimeState
// 0x0014 (0x0014 - 0x0000)
struct FMusicalPlayerRuntimeState final
{
public:
	bool                                          Debug;                                             // 0x0000(0x0001)(Edit, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsTriggered;                                       // 0x0001(0x0001)(Edit, ZeroConstructor, Transient, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsPlaying;                                         // 0x0002(0x0001)(Edit, ZeroConstructor, Transient, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsPaused;                                          // 0x0003(0x0001)(Edit, ZeroConstructor, Transient, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsFinished;                                        // 0x0004(0x0001)(Edit, ZeroConstructor, Transient, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         SecondsUntilNextPlay;                              // 0x0008(0x0004)(Edit, ZeroConstructor, Transient, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ElapsedMs;                                         // 0x000C(0x0004)(Edit, ZeroConstructor, Transient, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ActiveTriggerTickets;                              // 0x0010(0x0004)(Edit, ZeroConstructor, Transient, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.StartCondition
// 0x0010 (0x0010 - 0x0000)
struct FStartCondition final
{
public:
	EAudioClipStartPosition                       StartPosition;                                     // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EMusicalSubdivision                           Subdivision;                                       // 0x0001(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Dotted;                                            // 0x0002(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Triplet;                                           // 0x0003(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         TickOffset;                                        // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EWaitAtLeastMode                              AtLeastMode;                                       // 0x0008(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         WaitAtLeast;                                       // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.CursorSettings
// 0x0030 (0x0030 - 0x0000)
struct FCursorSettings final
{
public:
	class FString                                 eventSourceName;                                   // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 trackName;                                         // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EFLookAheadType                               lookAheadType;                                     // 0x0020(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         lookAheadTicks;                                    // 0x0024(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         lookAheadMs;                                       // 0x0028(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          broadcastTextMsgs;                                 // 0x002C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          broadcastNoteOnMsgs;                               // 0x002D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          broadcastNoteOffMsgs;                              // 0x002E(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          broadcastPitchbendMsgs;                            // 0x002F(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.MusicClipSyncConfig
// 0x0018 (0x0018 - 0x0000)
struct FMusicClipSyncConfig final
{
public:
	EMusicClipSyncOptions                         SyncOption;                                        // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EMusicClipTimelineMapping                     timelineMapping;                                   // 0x0001(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2[0x2];                                        // 0x0002(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         offsetTicks;                                       // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         minWaitTicks;                                      // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         minWaitMs;                                         // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ignoreMasterLoopsAndSeeks;                         // 0x0010(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          continueIfMasterStops;                             // 0x0011(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EMusicClipUnmutePoint                         unmutePoint;                                       // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_13[0x1];                                       // 0x0013(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         maxPreRollBars;                                    // 0x0014(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.MusicClipSpeedConfig
// 0x000C (0x000C - 0x0000)
struct FMusicClipSpeedConfig final
{
public:
	EMusicClipSpeedConfigMode                     Mode;                                              // 0x0000(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Speed;                                             // 0x0004(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          maintainPitch;                                     // 0x0008(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ignoreTimeAuthoritysPitchMaintainence;             // 0x0009(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A[0x2];                                        // 0x000A(0x0002)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct HmxAudio.TrackChannelSpecifier
// 0x0018 (0x0018 - 0x0000)
struct FTrackChannelSpecifier final
{
public:
	class FString                                 trackName;                                         // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         MidiChannelFlags;                                  // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct HmxAudio.TrackArgs
// 0x0030 (0x0030 - 0x0000)
struct FTrackArgs final
{
public:
	TSoftObjectPtr<class USynthesizerPatchAssetBase> SynthPatch;                                     // 0x0000(0x0028)(BlueprintVisible, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         BeatLength;                                        // 0x0028(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct HmxAudio.TrackPageSave
// 0x0010 (0x0010 - 0x0000)
struct FTrackPageSave final
{
public:
	TArray<int32>                                 EnabledSquares;                                    // 0x0000(0x0010)(Edit, ZeroConstructor, SaveGame, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.SequencerTrackSave
// 0x0010 (0x0010 - 0x0000)
struct FSequencerTrackSave final
{
public:
	TArray<struct FTrackPageSave>                 SavedPages;                                        // 0x0000(0x0010)(Edit, ZeroConstructor, SaveGame, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.SequencerSave
// 0x0010 (0x0010 - 0x0000)
struct FSequencerSave final
{
public:
	TArray<struct FSequencerTrackSave>            SavedTracks;                                       // 0x0000(0x0010)(Edit, ZeroConstructor, SaveGame, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.PBSetting
// 0x0008 (0x0008 - 0x0000)
struct FPBSetting final
{
public:
	int32                                         midiChannel;                                       // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Value;                                             // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.CCSetting
// 0x000C (0x000C - 0x0000)
struct FCCSetting final
{
public:
	int32                                         midiChannel;                                       // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EMidiControllerID                             Control;                                           // 0x0004(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Value;                                             // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.HarmonixAnalyzerOutputSettings
// 0x0010 (0x0010 - 0x0000)
struct FHarmonixAnalyzerOutputSettings final
{
public:
	float                                         RiseMs;                                            // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         FallMs;                                            // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MaxDB;                                             // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         RangeDB;                                           // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.HarmonixAnalyzerFFTSettings
// 0x002C (0x002C - 0x0000)
struct FHarmonixAnalyzerFFTSettings final
{
public:
	bool                                          Enabled;                                           // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         MinFrequencyHz;                                    // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MaxFrequencyHz;                                    // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          EqualLoudnessWeights;                              // 0x000C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          MelScaleBinning;                                   // 0x000D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_E[0x2];                                        // 0x000E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         NumResultBins;                                     // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         FftLength;                                         // 0x0014(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FHarmonixAnalyzerOutputSettings        OutputSettings;                                    // 0x0018(0x0010)(Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_28[0x4];                                       // 0x0028(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct HmxAudio.HarmonixFilterBankBandSettings
// 0x0018 (0x0018 - 0x0000)
struct FHarmonixFilterBankBandSettings final
{
public:
	float                                         StartHz;                                           // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         EndHz;                                             // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FHarmonixAnalyzerOutputSettings        OutputSettings;                                    // 0x0008(0x0010)(Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.HarmonixAnalyzerEffectSettings
// 0x00B0 (0x00B0 - 0x0000)
struct FHarmonixAnalyzerEffectSettings final
{
public:
	class FName                                   InstanceName;                                      // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          VuEnabled;                                         // 0x0004(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         VuAvgWindowMs;                                     // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         VuPeakHoldMs;                                      // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FHarmonixAnalyzerOutputSettings        VuOutputSettings;                                  // 0x0010(0x0010)(Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	bool                                          DrEnabled;                                         // 0x0020(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         DrHighRisingAlpha;                                 // 0x0024(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DrHighFallingAlpha;                                // 0x0028(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DrLowRisingAlpha;                                  // 0x002C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DrLowFallingAlpha;                                 // 0x0030(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         DrWindowSize;                                      // 0x0034(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          DrFilterResult;                                    // 0x0038(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_39[0x3];                                       // 0x0039(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         DrFilterCutoff;                                    // 0x003C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FHarmonixAnalyzerFFTSettings           FftSettings;                                       // 0x0040(0x002C)(Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	bool                                          FilterBankEnabled;                                 // 0x006C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_6D[0x3];                                       // 0x006D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FHarmonixFilterBankBandSettings> FilterBankBands;                                  // 0x0070(0x0010)(Edit, BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
	bool                                          SemitonesEnabled;                                  // 0x0080(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_81[0x3];                                       // 0x0081(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         SemitonesMidiNoteMin;                              // 0x0084(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         SemiTonesMidiNoteRange;                            // 0x0088(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FHarmonixAnalyzerOutputSettings        SemiTonesOutputSettings;                           // 0x008C(0x0010)(Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	bool                                          WaveformEnabled;                                   // 0x009C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9D[0x3];                                       // 0x009D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         WaveformNumBinsHeld;                               // 0x00A0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         WaveformNumBinsPerSecond;                          // 0x00A4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         WaveformSmoothingFactor;                           // 0x00A8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         WaveformSmoothingDistance;                         // 0x00AC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.HarmonixAnalyzerEffectResults
// 0x0080 (0x0080 - 0x0000)
struct FHarmonixAnalyzerEffectResults final
{
public:
	TArray<float>                                 VuChLevels;                                        // 0x0000(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, NativeAccessSpecifierPublic)
	TArray<float>                                 VuChPeaks;                                         // 0x0010(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, NativeAccessSpecifierPublic)
	float                                         VuMonoLevel;                                       // 0x0020(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         VuMonoPeak;                                        // 0x0024(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         VuMonoPeakdB;                                      // 0x0028(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DrHighEnvelope;                                    // 0x002C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DrLowEnvelope;                                     // 0x0030(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DrDb;                                              // 0x0034(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DrMonoPeakdB;                                      // 0x0038(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DrMonoPeakHighEnvelopedB;                          // 0x003C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<float>                                 FftLevels;                                         // 0x0040(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, NativeAccessSpecifierPublic)
	TArray<float>                                 FilterBankLevels;                                  // 0x0050(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, NativeAccessSpecifierPublic)
	uint8                                         Pad_60[0x10];                                      // 0x0060(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 Waveform;                                          // 0x0070(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.HmxPerPlatformConfig
// 0x0004 (0x0004 - 0x0000)
struct FHmxPerPlatformConfig final
{
public:
	int32                                         numAudioRenderThreads;                             // 0x0000(0x0004)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.AudioParam
// 0x0020 (0x0020 - 0x0000)
struct alignas(0x08) FAudioParam final
{
public:
	class FName                                   Name;                                              // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Value;                                             // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          isDefined;                                         // 0x0008(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x17];                                       // 0x0009(0x0017)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct HmxAudio.InitialVolumeSettings
// 0x0010 (0x0010 - 0x0000)
struct FInitialVolumeSettings final
{
public:
	bool                                          modifyAtStart;                                     // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Volume;                                            // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         TransitionTime;                                    // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EPostFadeOptionEnum                           postFadeOption;                                    // 0x000C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct HmxAudio.PlayArgs
// 0x0040 (0x0040 - 0x0000)
struct FPlayArgs
{
public:
	uint8                                         Pad_0[0x8];                                        // 0x0000(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UMusicEmitterComponent*                 Emitter;                                           // 0x0008(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          paused;                                            // 0x0010(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          muted;                                             // 0x0011(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_12[0x2];                                       // 0x0012(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FInitialVolumeSettings                 volumeSettings;                                    // 0x0014(0x0010)(Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	class FName                                   RenderTarget;                                      // 0x0024(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   mixPreset;                                         // 0x0028(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FAudioParam>                    initialParams;                                     // 0x0030(0x0010)(Edit, BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
};

// ScriptStruct HmxAudio.MusicSyncConfig
// 0x0028 (0x0028 - 0x0000)
struct FMusicSyncConfig final
{
public:
	EFMusicSyncOptions                            SyncOption;                                        // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          oneShot;                                           // 0x0001(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UMusicHandle*                           timeAuthorityHandle;                               // 0x0008(0x0008)(BlueprintVisible, ZeroConstructor, Transient, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EFMusicTimelineMapping                        timelineMapping;                                   // 0x0010(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         offsetTicks;                                       // 0x0014(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         minWaitTicks;                                      // 0x0018(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         minWaitMs;                                         // 0x001C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EFMusicUnmutePoint                            unmutePoint;                                       // 0x0020(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct HmxAudio.MusicSpeedConfig
// 0x0008 (0x0008 - 0x0000)
struct FMusicSpeedConfig final
{
public:
	float                                         Speed;                                             // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          maintainPitch;                                     // 0x0004(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct HmxAudio.PlayMusicArgs
// 0x0068 (0x00A8 - 0x0040)
struct FPlayMusicArgs final : public FPlayArgs
{
public:
	TSoftObjectPtr<class UMusicAssetBase>         playableAsset;                                     // 0x0040(0x0028)(Edit, BlueprintVisible, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FMusicSyncConfig                       syncConfig;                                        // 0x0068(0x0028)(Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	struct FMusicSpeedConfig                      speedConfig;                                       // 0x0090(0x0008)(Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	float                                         PitchMultiplier;                                   // 0x0098(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         transposition;                                     // 0x009C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EFStretcherAlgorithm                          overridingStretchAlgorithm;                        // 0x00A0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EFFormantHandling                             overridingFormantHandling;                         // 0x00A1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A2[0x6];                                       // 0x00A2(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// ScriptStruct HmxAudio.PlayInstrumentArgs
// 0x0038 (0x0078 - 0x0040)
struct FPlayInstrumentArgs final : public FPlayArgs
{
public:
	EFInstrumentRenderMode                        renderMode;                                        // 0x0040(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UInstrumentHandle*                      parentHandle;                                      // 0x0048(0x0008)(BlueprintVisible, ZeroConstructor, Transient, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSoftObjectPtr<class USynthesizerPatchAssetBase> playableAsset;                                  // 0x0050(0x0028)(Edit, BlueprintVisible, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

