#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: JoinServer

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass JoinServer.JoinServer_C
// 0x0010 (0x0580 - 0x0570)
class UJoinServer_C final : public UFortUIStateWidget_JoinServer
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0570(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBuildWatermark_C*                      BuildWatermark;                                    // 0x0578(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void OnShowTutorialDialog();
	void OnEnterState(EFortUIState PreviousUIState);
	void ExecuteUbergraph_JoinServer(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"JoinServer_C">();
	}
	static class UJoinServer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UJoinServer_C>();
	}
};

}

