#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ProgressiveStageListView

#include "Basic.hpp"

#include "CrewUI_classes.hpp"
#include "SlateCore_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ProgressiveStageListView.ProgressiveStageListView_C
// 0x0020 (0x0418 - 0x03F8)
class UProgressiveStageListView_C final : public UFortProgressiveStageList
{
public:
	class UProgressiveStageWidget_C*              ProgressiveStageList;                              // 0x03F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UProgressiveStageWidget_C*              ProgressiveStageList_1;                            // 0x0400(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UProgressiveStageWidget_C*              ProgressiveStageList_2;                            // 0x0408(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VBox_StagesContainer;                              // 0x0410(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	class UFortProgressiveStageWidget* AddStageWidget();
	void ClearStageWidgets();
	class UWidget* On_Stage_Widget_Custom_Boundary(EUINavigation Navigation_0);
	void Update_Subscribed_Visuals(bool Is_Subscribed);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ProgressiveStageListView_C">();
	}
	static class UProgressiveStageListView_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UProgressiveStageListView_C>();
	}
};

}

