#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_PinnedQuestMarkerIndicator

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "FortniteGame_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_PinnedQuestMarkerIndicator.W_PinnedQuestMarkerIndicator_C
// 0x0018 (0x0620 - 0x0608)
class UW_PinnedQuestMarkerIndicator_C final : public UAthenaMarkedActorIndicator
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0608(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       ShowHide;                                          // 0x0610(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 Pin;                                               // 0x0618(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void Construct();
	void ExecuteUbergraph_W_PinnedQuestMarkerIndicator(int32 EntryPoint);
	float GetRemovalDuration();
	void NotifyWillBeRemoved();
	void PreConstruct(bool IsDesignTime);

	class UCanvasPanel* GetCanvasPanelContainer(EFortActorIndicatorContainerWidget ContainerEnum) const;
	class AActor* GetIndicatedActor() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_PinnedQuestMarkerIndicator_C">();
	}
	static class UW_PinnedQuestMarkerIndicator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_PinnedQuestMarkerIndicator_C>();
	}
};

}

